version: 2.1

orbs:
  node: circleci/node@3.0.0
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11
  aws-cli: circleci/aws-cli@0.1.15



workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
            account-url: '872144589073.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-scan-test'
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            dockerfile: Dockerfile
            path: './'
            region: AWS_REGION
            repo: circleci-ecr-orb-demo
      - filters:
          branches:
            - only: develop
#      - build-server:
#          filters:
#            branches:
#              only: develop
