version: 2.1

orbs:
  node: circleci/node@3.0.0
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy using AWS CodeDeploy
          command: |
            aws ecs update-service --force-new-deployment --cluster test --service test-service

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          path: './'
          region: AWS_REGION
          repo: ecr-scan-test
          tag: 1.0.4
      - deploy:
          requires:
            - build_and_push_image
          filters:
            branches:
              only: develop

